### ISSUE TITLE
Doesn't run?

### ISSUE THREAD

**Issue by gsnedders** [test262-utils/test262-harness-py#8]
```
python test262.py --help
Traceback (most recent call last):
  File "test262.py", line 31, in <module>
    from parseTestRecord import parseTestRecord, stripHeader
ImportError: cannot import name stripHeader
```

`stripHeader` indeed seems to be undefined?

**Comment by gsnedders** [comment]
Regression from #4, previously reported in [comment there](https://github.com/test262-utils/test262-harness-py/pull/4#issuecomment-514269086). cc/ @caitp @anba

**Comment by caitp** [comment]
I can’t really comment on this, as the only verification of the patch I did was using v8’s test runner, which didn’t hit the problem.

I guess the right fix is to update the stripHeader calls to the new thing, or else re-export it.

**Comment by jsjzgy** [comment]
I also encountered this problem, but I don’t know how to solve it, can anyone give a solution?

**Comment by cclauss** [comment]
`stripHeader` was removed in #4

Confirmed and reverted in #13 to fix failing pytests.

My hunch is that #4 also broke other tests.
